language: asm
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/c64lib/travis-ci/master/install.sh)
script:
  - ka cia.asm
  - ka vic2.asm
  - ka sprites.asm
notifications:
  email:
    on_success: change
    on_failure: change
