/*
 * Copper demo 1.
 */

#import "common/mem.asm"
#import "../cia.asm"
#import "../vic2.asm"
#import "../mos6510.asm"

.label IRQ_1 = 150
.label IRQ_2 = 200

.pc = $0801 "Basic Upstart"
:BasicUpstart(start) // Basic start routine

// Main program
.pc = $0810 "Program"

start:
  :debugBorder(YELLOW)

  sei
  // diasble CIA interrupts
  lda #$7f
  sta c64lib.CIA1_IRQ_CONTROL
  sta c64lib.CIA2_IRQ_CONTROL
  lda c64lib.CIA1_IRQ_CONTROL
  lda c64lib.CIA2_IRQ_CONTROL
  // enable IRQ generated by VIC-II
  lda #c64lib.IMR_RASTER
  sta c64lib.IMR
  :setRaster(IRQ_1)
  lda #<irq1
  sta c64lib.IRQ_LO
  lda #>irq1
  sta c64lib.IRQ_HI
  lda #<irqFreeze
  sta c64lib.NMI_LO
  lda #>irqFreeze
  sta c64lib.NMI_HI
  
  :debugBorder(RED)
  
  :configureMemory(c64lib.RAM_IO_RAM)
  
  :debugBorder(WHITE)
  
  cli
block:
  jmp block
  
irq1: {  
  :irqEnter()
  inc c64lib.BG_COL_0
  inc c64lib.BORDER_COL
  :irqExit(irq2, IRQ_2, false)
}  

irq2: {
  :irqEnter()
  dec c64lib.BG_COL_0
  dec c64lib.BORDER_COL
  :irqExit(irq1, IRQ_1, false)
}
  
irqFreeze: {
  rti
}


